services:
  jobmail:
    restart: unless-stopped
    build:
      context: ./src # Mude para o caminho correto
      dockerfile: Dockerfile # O Dockerfile está na pasta src
    environment:
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - POETRY_HOME=/usr/src/poetry
    command: poetry run python app.py # Altere para o comando correto
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${PGADMIN_PORT:-8081}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: eu@eu.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local
