name: Deploy Jobmail Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    environment: jobmail

    env:
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to jobmail and run docker compose
        run: |
          cd ./jobmail  # Navega até o diretório 'jobmail'
          echo "${{ secrets.SPASSWD }}" | sudo -S curl -s https://raw.githubusercontent.com/psousaj/small-projects/main/jobmail/install.sh | bash
