name: Deploy Jobmail Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    needs: build
    runs-on: self-hosted

    env:
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      DATABASE_USER: ${{ vars.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ vars.DATABASE_NAME }}
      DATABASE_HOST: ${{ vars.DATABASE_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: jobmail/app # Faz o checkout do repositório no diretório jobmail

      - name: Run docker container
        run: |
          cd jobmail  # Navega até o diretório jobmail
          docker compose up --build
