name: Deploy Jobmail Application

on:
  push:
    branches: [main]

jobs:
  deploy-jobmail:
    runs-on: self-hosted

    environment: jobmail

    env:
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to jobmail and run install script
        run: |
          cd ./jobmail
          echo "${{ secrets.SPASSWD }}" | bash install.sh
